
services:
  # ======================================
  # Contenedor de la primera aplicación
  # ======================================
  bogdan:
    build: ./bai0002                # Construye la imagen desde ./app1
    container_name: bai0002         # Nombre del contenedor
    ports:
      - " 8081:8082"                   # Expone el puerto 8081 solo dentro de la red de Docker

  # ======================================
  # Contenedor de la segunda aplicación
  # ======================================
  cesar:
    build: ./ccb0016
    container_name: ccb0016
    ports:
      - "8081:8083"

  # ======================================
  # Contenedor de la tercera aplicación
  # ======================================
  pilar:
    build: ./pml0015
    container_name: pml0015
    ports:
      - "8081:8084"

  # ======================================
  # Contenedor de la cuarta aplicación
  # ======================================
  sergio:
    build: ./sjp0005
    container_name: sjp0005
    ports:
      - "8081:8085"
