version: "3.9"

services:
  # ======================================
  # APP 1 - bai0002 (con login)
  # ======================================
  bogdan:
    build: ./bai0002
    container_name: bai0002
    environment:
      - LOGIN_USER=${LOGIN_USER}
      - LOGIN_PASS=${LOGIN_PASS}
      - SECRET2=${SECRET2}
    ports:
      - "8082:8081"   # host:contenedor
    networks:
      - app-network

  # ======================================
  # APP 2 - ccb0016
  # ======================================
  cesar:
    build: ./ccb0016
    container_name: ccb0016
    ports:
      - "8083:8081"
    networks:
      - app-network

  # ======================================
  # APP 3 - pml0015
  # ======================================
  pilar:
    build: ./pml0015
    container_name: pml0015
    ports:
      - "8084:8081"
    networks:
      - app-network

  # ======================================
  # APP 4 - sjp0005
  # ======================================
  sergio:
    build: ./sjp0005
    container_name: sjp0005
    ports:
      - "8085:8081"
    networks:
      - app-network

  # ======================================
  # NGINX (Reverse Proxy)
  # ======================================
  nginx:
    image: nginx:latest
    container_name: reverse-proxy
    ports:
      - "8081:80"  # host → Nginx
    volumes:
      - ./nginx:/etc/nginx:ro
    depends_on:
      - bogdan
      - cesar
      - pilar
      - sergio
    networks:
      - app-network

# ======================================
# Red interna para que Nginx acceda a los contenedores
# ======================================
networks:
  app-network:
    driver: bridge
