events {}

http {
    server {
        listen 8081;

        # Tu app Flask accesible en /bio0001/
        location /bai0002/ {
            proxy_pass http://flask-app:5000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_redirect off;
        }

        # Redirección opcional: si el usuario entra en /bio0001 sin la barra final
        location = /bai0002 {
            return 301 /bai0002/;
        }

        # Ejemplo adicional: subruta a GitHub
        location /github/ {
            return 302 https://github.com$request_uri;
        }
    }
}
