events {}

http {
    server {
        listen 80;

        # APP 1 - ccb0016 (servicio: cesar)
        location /ccb0016/ {
            proxy_pass http://ccb0016:8081/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # APP 2 - bai0002 (servicio: bogdan)
        location /bai0002/ {
            proxy_pass http://bai0002:8081/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # APP 3 - pml0015 (servicio: pilar)
        location /pml0015/ {
            proxy_pass http://pml0015:8081/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # APP 4 - sjp0005 (servicio: sergio)
        location /sjp0005/ {
            proxy_pass http://sjp0005:8081/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}

